# Generated by Django 5.2.6 on 2025-09-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=9, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField()),
                ('endereco', models.CharField()),
                ('numero', models.CharField()),
                ('complemento', models.CharField()),
                ('bairro', models.CharField()),
                ('uf', models.CharField(max_length=2)),
                ('numero_matricula', models.CharField(unique=True)),
                ('curso', models.CharField(max_length=20)),
                ('serie', models.CharField()),
                ('turno', models.CharField()),
                ('observacoes', models.TextField(max_length=200)),
            ],
        ),
    ]
