# Generated by Django 5.2.6 on 2025-09-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(default='desconhecido', max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('a', 'Apicultura'), ('b', 'Alimentos'), ('i', 'Informática')], max_length=1),
        ),
    ]
