# Generated by Django 5.2.6 on 2025-09-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_cidade_alter_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
