# Generated by Django 5.2.6 on 2025-09-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_alter_aluno_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('apicultura', 'Apicultura'), ('alimentos', 'Alimentos'), ('informática', 'Informática')], max_length=15),
        ),
    ]
